# Created 2022-01-10 Mon 13:44
#+title: MIT anaphora seminar (Spring 2022)
#+author: Patrick D. Elliott
#+bibliography: ../bibliography/master.bib
#+setupfile: latex-template.org
#+cite_export: csl

* Topics (tbc)

Last updated: "[2022-01-10 Mon 13:44]" 

** Discourse referents and dynamic notions of content

- ([[citeproc_bib_item_16][Heim 1982]])
- ([[citeproc_bib_item_15][Groenendijk and Stokhof 1991]])
- ([[citeproc_bib_item_13][Groenendijk, Stokhof, and Veltman 1996]])
- ([[citeproc_bib_item_7][Dekker 1994]])
- ([[citeproc_bib_item_5][Chierchia 1995]])

** Integrating dynamic and compositional semantics

- ([[citeproc_bib_item_14][Groenendijk and Stokhof 1990]])
- ([[citeproc_bib_item_22][Muskens 1996]])
- ([[citeproc_bib_item_3][Charlow 2014]])

** Negation and disjunction

- ([[citeproc_bib_item_27][Simons 1996]])
- ([[citeproc_bib_item_20][Krahmer and Muskens 1995]])
- ([[citeproc_bib_item_12][Gotham 2019]])
- ([[citeproc_bib_item_17][Hofmann 2019]])

** Predictive dynamics

- ([[citeproc_bib_item_26][Schlenker 2010]])
- ([[citeproc_bib_item_25][Schlenker 2009]])
- ([[citeproc_bib_item_24][Schlenker 2008]])
- ([[citeproc_bib_item_4][Charlow 2019]])
- ([[citeproc_bib_item_11][Elliott 2020b]])
- ([[citeproc_bib_item_21][Mandelkern 2020]])

** Plurality and maximality

- ([[citeproc_bib_item_1][van den Berg 1996]])
- ([[citeproc_bib_item_2][Brasoveanu 2007]])
- ([[citeproc_bib_item_19][Keshet 2018]])

** Dynamic inquisitive semantics

- ([[citeproc_bib_item_9][Dotlačil and Roelofsen 2019]])
- ([[citeproc_bib_item_8][Dotlacil and Roelofsen 2021]])

** Dynamic semantics and the grammar

*** Crossover

- ([[citeproc_bib_item_6][Chierchia 2020]])
- ([[citeproc_bib_item_10][Elliott 2020a]])

*** Binding theory

- ([[citeproc_bib_item_23][Schlenker 2005]])

*** Weak islands and intervention effects

- ([[citeproc_bib_item_18][Honcoop 1998]])

* References

<<citeproc_bib_item_1>>Berg, M. H. van den. 1996. “Some Aspects of the Internal Structure of Discourse. The Dynamics of Nominal Anaphora.” https://dare.uva.nl/search?arno.record.id=7073.

<<citeproc_bib_item_2>>Brasoveanu, Adrian. 2007. “Structured Nominal and Modal Reference.” PhD thesis, Rutgers University - Graduate School - New Brunswick.

<<citeproc_bib_item_3>>Charlow, Simon. 2014. “On the Semantics of Exceptional Scope.” PhD thesis, New Brunswick: Rutgers University.

<<citeproc_bib_item_4>>———. 2019. “Static and Dynamic Exceptional Scope.” lingbuzz/004650.

<<citeproc_bib_item_5>>Chierchia, Gennaro. 1995. /Dynamics of Meaning - Anaphora, Presupposition, and the Theory of Grammar/. Chicago: University of Chicago Press.

<<citeproc_bib_item_6>>———. 2020. “Origins of Weak Crossover - When Dynamic Semantics Meets Event Semantics.” /Natural Language Semantics/, no. 28: 23–76.

<<citeproc_bib_item_7>>Dekker, Paul. 1994. “Predicate Logic with Anaphora.” /Semantics and Linguistic Theory/ 4 (November): 79–95. https://doi.org/10.3765/salt.v4i0.2459.

<<citeproc_bib_item_8>>Dotlacil, Jakub, and Floris Roelofsen. 2021. “A Dynamic Semantics of Single-Wh and Multiple-Wh Questions.” /Semantics and Linguistic Theory/ 30 (0, 0): 376–95. https://doi.org/10.3765/salt.v30i0.4839.

<<citeproc_bib_item_9>>Dotlačil, Jakub, and Floris Roelofsen. 2019. “Dynamic Inquisitive Semantics: Anaphora and Questions.” /Proceedings of Sinn Und Bedeutung/, July, 365–82 Pages. https://doi.org/10.18148/SUB/2019.V23I1.538.

<<citeproc_bib_item_10>>Elliott, Patrick D. 2020a. “Crossover and Accessibility in Dynamic Semantics.” MIT: lingbuzz/005311. https://ling.auf.net/lingbuzz/005311.

<<citeproc_bib_item_11>>———. 2020b. “Towards a Principled Logic of Anaphora.” MIT: lingbuzz/005562. https://ling.auf.net/lingbuzz/005562.

<<citeproc_bib_item_12>>Gotham, Matthew. 2019. “Double Negation, Excluded Middle and Accessibility in Dynamic Semanttics.” In /Proceedings of the 22nd Amsterdam Colloquium/, edited by Julian J. Schlöder, Dean McHugh, and Floris Roelofsen, 142–51.

<<citeproc_bib_item_13>>Groenendijk, Jeroen a. G., Martin J. B. Stokhof, and Frank J. M. M. Veltman. 1996. “Coreference and Modality.” In /The Handbook of Contemporary Semantic Theory/, 176–216. Blackwell Handbooks in Linguistics. Oxford: Blackwell. https://dare.uva.nl/search?identifier=c655089e-9fae-4842-90da-30e46f37825b.

<<citeproc_bib_item_14>>Groenendijk, Jeroen, and Martin Stokhof. 1990. “Dynamic Montague Grammar.” Report. https://eprints.illc.uva.nl/id/eprint/1148/.

<<citeproc_bib_item_15>>———. 1991. “Dynamic Predicate Logic.” /Linguistics and Philosophy/ 14 (1): 39–100. https://www.jstor.org/stable/25001418.

<<citeproc_bib_item_16>>Heim, Irene. 1982. “The Semantics of Definite and Indefinite Noun Phrases.” PhD thesis, University of Massachusetts - Amherst.

<<citeproc_bib_item_17>>Hofmann, Lisa. 2019. “The Anaphoric Potential of Indefinites under Negation and Disjunction.” In /Proceedings of the 22nd Amsterdam Colloquium/, edited by Julian J. Schlöder, Dean McHugh, and Floris Roelofsen, 181–90.

<<citeproc_bib_item_18>>Honcoop, Martin. 1998. “Dynamic Excursions on Weak Islands.” PhD thesis, University of Leiden.

<<citeproc_bib_item_19>>Keshet, Ezra. 2018. “Dynamic Update Anaphora Logic - A Simple Analysis of Complex Anaphora.” /Journal of Semantics/ 35 (2): 263–303. https://doi.org/10.1093/jos/ffx020.

<<citeproc_bib_item_20>>Krahmer, Emiel, and Reinhard Muskens. 1995. “Negation and Disjunction in Discourse Representation Theory.” /Journal of Semantics/ 12 (4): 357–76. https://doi.org/10.1093/jos/12.4.357.

<<citeproc_bib_item_21>>Mandelkern, Matthew. 2020. “Witnesses.” Unpublished manuscript. Oxford: Unpublished manuscript.

<<citeproc_bib_item_22>>Muskens, Reinhard. 1996. “Combining Montague Semantics and Discourse Representation.” /Linguistics and Philosophy/ 19 (2): 143–86. https://doi.org/10.1007/BF00635836.

<<citeproc_bib_item_23>>Schlenker, Philippe. 2005. “Non-Redundancy: Towards a Semantic Reinterpretation of Binding Theory.” /Natural Language Semantics/ 13 (1): 1–92. https://doi.org/10.1007/s11050-004-2440-1.

<<citeproc_bib_item_24>>———. 2008. “Be Articulate: A Pragmatic Theory of Presupposition Projection.” /Theoretical Linguistics/ 34 (3). https://doi.org/10.1515/THLI.2008.013.

<<citeproc_bib_item_25>>———. 2009. “Local Contexts.” /Semantics and Pragmatics/ 2 (July). https://doi.org/10.3765/sp.2.3.

<<citeproc_bib_item_26>>———. 2010. “Local Contexts and Local Meanings.” /Philosophical Studies: An International Journal for Philosophy in the Analytic Tradition/ 151 (1): 115–42. https://doi.org/10.2307/40856594.

<<citeproc_bib_item_27>>Simons, Mandy. 1996. “Disjunction and Anaphora.” /Semantics and Linguistic Theory/ 6 (0, 0): 245–60. https://doi.org/10.3765/salt.v6i0.2760.
