#+title: File change semantics: context and composition
#+subtitle: HHU SoSe 2025
#+author: Patrick D. Elliott 
#+setupfile: handout-template.org
#+OPTIONS: ':t
#+cite_export: biblatex

* Introduction

** The topic of this seminar

#+begin_quote
"Consider a device designed to read a text in some natural language,
interpret it, and store the content in some manner, say, for the purpose
of being able to answer questions about it. To accomplish this task,
the machine will have to fulfill at least the following basic requirement.
It has to be able to build a file that consists of records of all the
individuals, that is, events, objects, etc., mentioned in the text and, for
each individual, record whatever is said about it. Of course, for the time being at least, it seems that such a text interpreter is not a practical idea, but this should not discourage us from studying in abstract what kind of capabilities the machine would have to possess, provided that our study
provides us with some insight into natural language in general." [cite:@Karttunen1976]
#+end_quote

- The notion of a /discourse referent/ emerged from the work of Lauri Karttunen and David Lewis [cite:@Karttunen1976;@Lewis1979a], during a time of general optimism concerning connections between linguistic theory and artificial intelligence research.
- The central idea is that discourse participants introduce and manipulate /variables/ corresponding to individuals mentioned over the course of a conversation.

#+name: example1
#+begin_exe
\ex A\(^x\) woman was bitten by a\(^y\) dog.
\ex She\(_x\) hit it\(_y\).
\ex It\(_y\) jumped over a\(^z\) fence.
#+end_exe

- This powerful idea subsequently informed dynamic approaches to meaning, which essentially model anaphora as a kind of cross-referencing device [cite:@Heim1982;@GroenendijkStokhof1991].
- In this course, we'll primarily be interested in /dynamic semantics/ proper, rather than discourse representation theories [cite:@Kamp1981], which are often grouped under the same umbrella.[fn:9]
- The dynamic slogan:

#+begin_quote
"You know the meaning of a sentence if you know the change it brings about in the information state of anyone who accepts the news conveyed by it" [cite:@Veltman1996a].
#+end_quote

** Logistics

*** Reading

- The first half of Chapter 3 of Irene Heim's 1982 MIT PhD dissertation "The semantics of definite and indefinite Noun Phrases", p178-211.
  * Note: make sure you use the 2011 typeset edition available to download here: https://semanticsarchive.net/Archive/jA2YTJmN
    
*** Question requirement

- in order to receive the BN for this course, you should remember to send me at least one question about each assigned reading, before the following week's (ideally, Monday evening at the latest).
  * Note: this doesn't have to be very sophisticated. Even just "Can you please go through this definition more slowly in class" is sufficient.
    
*** How this class might go


| date     | topic                          | reading                                                      |
|----------+--------------------------------+--------------------------------------------------------------|
| April 8  | File Change Semantics          | [cite:@Heim1982;@Heim1983b]                                  |
| April 15 | File Change Semantics ii       | [cite:@Heim1982;@Heim1983b]                                  |
| April 22 | Dynamic Predicate Logic        | [cite:@GroenendijkStokhof1991;@Gillies2022b]                 |
| April 29 | Dynamic Predicate Logic ii     | [cite:@GroenendijkStokhof1991;@Gillies2022b]                 |
| May 6    | Subsentential dynamics         | [cite:@GroenendijkStokhof1990a;@Charlow2020a] |
| May 13   | Subsentential dynamics ii      | [cite:@GroenendijkStokhof1990a;@Charlow2020a] |
| +May 20+   | No class                       |                                                              |
| May 27   | Anaphora and presupposition    | [cite:@Elliott2020f;@Elliott2023c]                           |
| June 3   | Anaphora and presupposition ii | [cite:@Elliott2020f;@Elliott2023c]                           |
| June 10  | Anaphora and modality          | [cite:@Elliott2023a]                                         |
| June 17  | Dynamic inquisitive semantics  | [cite:@DotlacilRoelofsen2019a;@DotlacilRoelofsen2021c]       |
| June 24  | Plural dynamic semantics       | [cite:@vandenBerg1996;@Nouwen2003a]                                                          |
| +July 1+   | No class                       |                                                              |
| July 8   | Student presentation           |                                                              |
| July 15  | Student presentation           |                                                              |

- We'll begin with Irene Heim's foundational work on /file change semantics/.
- This work - arguably the first real dynamic semantic theory - lead to an explosion of insightful research. 
- As we'll see, dynamic semantics incorporates powerful proprietary mechanisms for manipulating /contexts/ in an apparently arbitrary fashion.
- It even precompiles these mechanisms into the meanings of logical vocabulary such as "or".
- Part of this seminar will involve tracking developments in dynamic approaches to anaphora, starting from classical theories of (singular) pronouns and their indefinite antecedents, and eventually progressing to intricate theories of modality, plurality, and quantification.
- In parallel, we'll consider what exactly dynamic semantics commits us to, both as a theory of /content/, and as a theory of how semantic composition proceeds.
- A central goal will be a re-assessment of Veltman's slogan, in light of recent work that fine-tunes the division of labor between dynamic semantics and pragmatics [cite:@Elliott2020g;@Mandelkern2020c].  
  
* Linguistic motivations
** Pronoun puzzles

- Pronouns can be used /deictically/. The sentence in ([[deictic1]]) may be uttered, for example, while pointing at a corgi.

#+name: deictic1
#+begin_exe
\ex *It*'s playing outside.
#+end_exe

- Pronouns may also be interpreted as /bound variables/:

#+name: bound1
#+begin_exe 
\ex No girl wants to be like *her* mother.
#+end_exe

- An informal paraphrase of the meaning of ([[bound1]]) is: /no girl \(x\) is s.t., \(x\) wants to be like \(x\)'s mother/.
- Pronouns can also be /discourse anaphoric/ on an indefinite antecedent as in ([[discourse1]]). This is crucially not the same as the deictic use, as there does not have to be any salient individual present which the pronoun is intended to refer to.

#+name: discourse1
#+begin_exe
\ex A boy is waiting outside. Will you talk to *him*? 
#+end_exe

- In the past, these kinds of cases were taken to involve /coreference/, on the assumption that indefinites had a referential reading.
- There are some uses of pronouns which do not seem to involve coreference, nor be interpreted as bound variables.

#+name: ex:beg1
#+begin_exe
\ex Every philosopher who had *a question* asked *it*.
#+end_exe

- An attempt at solving this puzzle was to posit yet another reading of pronouns as covert definite descriptions (the "E-type" reading) [cite:@Evans1977].

#+name: ex:beg2
#+begin_exe
\ex Every philosopher who had *a question* asked *the question that he had*.
#+end_exe

- This was also intended to replace the referential analysis of cases like ([[discourse1]]).

#+name: ex:beg3
#+begin_exe
\ex A boy is waiting outside. Will you talk to *the boy waiting outside*?
#+end_exe

- A problem for the (simplest conception) of the E-type approach: failures of uniqueness.
- Heim's famous sage plant sentence poses a vivid illustration. Context: /sage plants are only sold in flats of nine/.

#+name: ex:sage
#+begin_exe
\ex Everyone who bought a sage plant here bought it together with eight others.
#+end_exe

- Other examples making a similar point (from [cite:@Kamp1981] and others):

#+name: ex:bishop
#+begin_exe
\ex When a bishop meets another bishop, he blesses him.
#+end_exe

#+name: ex:credit
#+begin_exe
\ex Everyone who had a credit card used it.
#+end_exe

#+name: ex:pen
#+begin_exe
\ex I have a pen. It's in my bag.
#+end_exe

- Assumption in dynamic semantics: pronouns are /always/ variables. Provide a uniform theory of all of these cases.

** Background to FCS: Pronouns as variables

- The received wisdom in classical semantics is that /pronouns are variables/ [cite:@HeimKratzer1998;@Montague1973a;@Buring2005a].
- A variable is a simple term whose denotation is dependent on an /assignment/, i.e., a function from variables to individuals. 
  * \(\eval*[g]{\text{her}_x} = g_x\)
-  For the time being, let's assume that assignments are /total functions/ from a stock of variables \(V\) to individuals. Assuming that \(V = \set{x,y,z}\), some possible assignments:


\[g_1 := \left[\begin{aligned}[c]
&x \to \mathtt{bunny}\\
&y \to \mathtt{louise}\\
&z \to \mathtt{popeye}
\end{aligned}
\right]
%
\quad
%
g_2 := \left[\begin{aligned}[c]
&x \to \mathtt{bunny}\\
&y \to \mathtt{bunny}\\
&z \to \mathtt{louise}
\end{aligned}
\right]
%
\quad
%
g_3 := \left[\begin{aligned}[c]
&x \to \mathtt{louise}\\
&y \to \mathtt{louise}\\
&z \to \mathtt{louise}
\end{aligned}
\right]
\]

- Some impossible assignments:

\[\left[\begin{aligned}[c]
&x \to \mathtt{bunny}\\
&y \to \mathtt{louise}\\
\end{aligned}
\right]
%
\quad
%
\left[
\right]\]

- Assignments are assumed to be /provided by the context/, the information provided by the context flows top-down, thanks to how functional applications are interpreted.

\[\eval*[g]{\alpha(\beta)} = \eval*[g]{\alpha}(\eval*[g]{\beta})\]

- This models (partially) the deictic use. A sentence with a deictic pronoun translates to a formula with a corresponding free variable. The resulting denotation is fundamentally assignment-sensitive.

\[\eval*[g]{\text{she}_x \text{ is playing outside} } = 1 \iff  g(x) \text{ is playing outside} \]

- In order to capture the bound-variable use, we introduce a special kind of composition rule - namely, /predicate abstraction/ [cite:@HeimKratzer1998].[fn:1] 

\[\eval*[g]{[\lambda x\,\alpha]} = f\text{ such that }f(a) = \eval*[g^{[x \to a]}]{\alpha }\] 

- The abstraction parameter manipulates the assignment of interpretation.

#+begin_quote
"We can think of an assignment as a store [...] that
assigns values to variables, with the role of \(.^{[x \to a]}\) being that of updating the store." [cite:@Carpenter1998]
#+end_quote

\[\left[\begin{aligned}[c]
&x \to \mathtt{bunny}\\
&y \to \mathtt{louise}\\
&z \to \mathtt{popeye}
\end{aligned}
\right]^{[y \to \mathtt{bunny}]}  = \left[\begin{aligned}[c]
&x \to \mathtt{bunny}\\
&y \to \mathtt{bunny}\\
&z \to \mathtt{popeye}
\end{aligned}
\right]\]

- This allows us to capture /bound variable interpretations/, assuming that certain expressions trigger the rule of predicate abstraction.
- Consider the following sentence:
  * Standard assumption: the index on "some dog" is interpreted as a lambda abstractor.

#+name: 
#+begin_exe
\ex [Some dog]\(_x\) chases it\(_x\)s tail.
#+end_exe

- \(\eval{some dog} = \lambda P_{et} \,.\,\exists x, x\text{ is a dog and }P(x) = 1 \)
  
#+begin_export latex
\begin{forest}
[{\(\textcircled{3}\)}
  [{} [{some dog},roof]]
  [{\(\textcircled{2}\)}
    [{\(\lambda x\)}]
    [{\(\textcircled{1}\)\\\(= 1\text{ at }g\text{ iff }g(x)\text{ chases }g(x)\text{'s tail}    \)} [{\(t_x\) chases \(x\)'s tail},roof]]
]
]
\end{forest}
#+end_export

- \(\eval[g^{[x \to \text{Bunny}]}]{\textcircled{1}} = 1 \iff \text{Bunny chases Bunny's tail} \)
- \(\eval[g^{[x \to \text{Louise}]}]{\textcircled{1}} = 1 \iff \text{Louise chases Louise's tail} \)
- \(\eval[g]{\textcircled{2}} = \lambda x_e \,.\,x\text{ chases }x\text{'s tail}  \)

#+begin_export latex
\[\eval[g]{\textcircled{3}} = \begin{aligned}[t]
&[ \lambda P_et \,.\,\exists x, x\text{ is a dog and }P(x) = 1 ]( \lambda x_e \,.\,x\text{ chases }x\text{'s tail}  )\\
&= 1 \iff \exists x,x\text{ is a dog and }x\text{ chases }x\text{'s tail}    
\end{aligned}\] 
#+end_export

- In order to get the bound variable interpretation, the pronoun must be /in the syntactic scope of a lambda abstractor with a matching variable index./
  
* The dynamic notion of content
** Stalnakerian pragmatics

- Our account of deictic pronouns is incomplete in a way which relates to how we account for discourse anaphora (what does it mean for an assignment function to be "furnished by the context?").
- We'll build on Stalnaker's influential proposal [cite:@Stalnaker1976a;@Stalnaker2002a]  that conversational contexts can be modeled as sets of possible worlds - the worlds that are accepted by the participants of a conversation.
- The Stalnakerian notion of context bundles all information into a single format - propositional content.
- The ignorance/initial state is logical space \(W\), and the absurd state is the empty set.
- Update is defined as follows (in a bivalent setting - we discuss presupposition later on):

\[c[\alpha] = c \cap \set{w | \eval*{\phi}(w) = 1}\]

- A brief illustration: consider a universe in which the only facts concern whether it's snowing and or raining.

\[W = \set{w_\emptyset , w_s, w_r, w_{sr}}\]

\[c[\text{it's raining} ] = W \cap \set{w_r,w_{rs}} = \set{w_r,w_{rs}}\]
 
** File contexts: the intuition

- The /dynamic/ notion of contexts is a extension of the Stalnakerian notion [cite:@Karttunen1976;@Lewis1979a;@Heim1982].
- The basic idea is that certain expressions, such as indefinites, trigger a representation consisting of a placeholder/label together with some information associated with that label. 
- Consider the following contrast:

#+begin_exe
\ex David is raconteuring. ??I heard *it* before.<<david1>>
\ex David is telling *a story*. I heard *it* before.<<david2>>
#+end_exe

- Although an idealization, let's assume, for the sake of argument that the sentences "David is raconteuring" and "David is telling a story" are contextually equivalent.
- This means that they should induce the same change in \(c\) - so why is it that ([[david1]]) sounds odd, in comparison to ([[david2]])?
- The dynamic solution: content is sensitive not just to what is conveyed, but /how/ it is conveyed.
- The sentence "David is telling *a story*" triggers the creation of a new label \(x\), with the information that \(x\) is a story told by David. The subsequent sentence "I heard *it* before" adds the information that the speaker heard \(x\) before.
- The file metaphor: variables correspond to files. Utterances with indefinites and pronouns trigger (i) the creation of a new file, and (ii) filing information in an existing file (respectively).

#+begin_quote
"A listener's task of understanding what is being said in the course of a conversation bears relevant similarities to a file clerk's task. Speaking metaphorically, let me say that to understand an utterance is to keep a file which, at every time in the course of the utterance, contains the information that has so far been conveyed by the utterance." [cite:@Heim1983b]
#+end_quote


** Modeling file contexts

- A way of modeling this using conceptual primitives we're familiar with: a /file/ is a set of world-assignment pairs (we'll refine this in a little while).

\[F_4 = \set{(w,g) | g_x \text{ is a story told by David in }w }\]

- This will be a set consisting of worlds where there exists some story told by David \(s\), paired with assignments where the variable \(x\) is mapped to \(s\).
- The file corresponding to "David is raconteuring" will, by conjecture, just contain the following. N.b. that \(g\) isn't mentioned in the predicate.

\[F_5 = \set{(w,g) | \text{there's a story told by David in }w  }\]

*** Truth of a file

#+begin_definition
Truth of a file.

\[\mathbf{true}_w(F) \iff \exists g[(w,g) \in F]\]
#+end_definition

*** World set

- We can now give a useful definition: the /world set/ of a file (following [cite:@Heim1982]).

#+begin_definition
The world set of a file $F$, $F_w$, is defined as follows:[fn:2]

\[F_w = \set{w | (w,*) \in F}\]
#+end_definition

- \(F_4,w = F_5,w\) - both convey the information that David is telling a story.
  * For \(F_5\) this is trivial.
  * For \(F_4\), this is because each world in the file must contain some story \(s\) told by David, so that the paired assignment can map \(x\) to \(s\).  
  
*** Satisfaction set
  
- Another useful definition is the /satisfaction set/ of a particular world in a file.

#+begin_definition
The satisfaction set at file \(F\) of a world \(w \in F\), \(\mathbf{sat}_F(w)\), is defined as follows:

\[\mathbf{sat}_F(w) = \set{g | (w,g) \in F}\]
#+end_definition

- \(\mathbf{sat}_F\) maps worlds to the set of the assignments they are paired with in \(F\). 
- Every world \(w \in F_5\) is mapped to an empty satisfaction set. 
- Each world \(w \in F_4\) is mapped to the set of assignments which map \(x\) to a story told by David in \(w\). N.b. in some worlds, David may tell multiple stories, in which case the satisfaction set will contain many such assignments.
- Imagine that the initial context contains at least the following worlds:
  * \(w_1\): David tells exactly one story, \(s_1\)
  * \(w_2\): David tells exactly one story, \(s_2\)
  * \(w_{12}\): David tells two stories, \(s_1,s_2\)
  * \(w_{\emptyset }\): David doesn't tell any stories, \(s_1,s_2\)
- The file of the context after an utterance of "David is telling a\(_x\) story", will contain (at least) the following information:

\[F = \begin{aligned}[t]
&\set{(w_1,g)|g_x = s_1}\\
&\cup \set{(w_2,g)|g_x = s_2}\\
&\cup \set{(w_{12},g)|g_x = s_1}\\
&\cup \set{(w_{12},g)|g_x = s_2}
\end{aligned}
\] 

#+begin_tcolorbox
Compute the satisfaction sets of each of \(w_1\), \(w_2\) and \(w_{12}\) at \(F\).
#+end_tcolorbox

* File change semantics: the basics

** Context Change Potentials

- Heim's conjecture: sentences /by virtue of their semantic value/ operate directly on file contexts, hence - /file change semantics/.
  * The "dynamic slogan" (mentioned in the syllabus):

#+begin_quote
"You know the meaning of a sentence if you know the change it brings about in the information state of anyone who accepts the news conveyed by it" [cite:@Veltman1996a]
#+end_quote

- Sentential meanings, for Heim will be /functions from files to files/, which she calls /Context Change Potentials/ (CCPs).
- So far we haven't said anything about indefinites vs. definites. Here's the intuition we'd like to capture:
  * Indefinites introduce new labels in the file, and may not add information to existing labels. Considering the following example:

#+name: novelty1
#+begin_exe
\ex \(\#\)A\(_x\) man walked in. A\(_x\) man sat down.
\ex A\(_x\) man walked in. A\(_y\) man sat down.
#+end_exe

** /Novelty/ as a file-level notion

- One way of understanding this is that "A\(_x\) man sat down" is infelicitous if uttered after "A\(_x\) man walked in", however "A\(_y\) man sat down" is felicitous if uttered after "A\(_x\) man walked in".
- As Heim explains, we can check whether or not a variable \(x\) is "unused" in a file, if the file never discriminates between assignments that differ only at \(x\).

#+name: def:novelty
#+begin_definition
Novelty of a variable with respect to a file.
\[\mathbf{nov}_F(x) \iff  \forall w, \forall g, \forall g'[g[x]g' \rightarrow ((w,g) \in F \iff (w,g') \in F)]\]
#+end_definition

- In more informal terms: a variable \(x\) is /novel/ with respect to a file \(F\) iff, for any two assignments \(g\) and \(g'\) which differ /only/ in the value they assign to \(x\), \(F\) never distinguishes between \((w,g)\) and \((w,g')\), for any world \(w\).
- First, we can ask, for an initial context \(c_\top\), whether any given variable counts as novel.
- If we define the initial, or ignorance context as the product of logical space and the set of possible assignments, then it is easy to see that every variable will indeed be novel with respect to \(c_\top\) - for every world \(w \in W\), and every assignment \(g \in D_g\), \((w,g) \in c_\top\), so \(c_\top\) never distinguishes between any assignments by definition. 

#+begin_fact
Given a stock of variables \(V\), \(\forall v \in V[\mathbf{nov}_{c_\top}(v)]\).
#+end_fact

- Consider how the initial context changes after an assertion of the sentence "a\(^x\) man walked in". We retain the world assignment pairs \((w,g) \in c_\top\), such that \(g\) assigns \(x\) to a man who walked in, in \(w\).

#+name: ex:manwalkedin
#+begin_exe
\ex \(c' = \set{(w,g)|g_x \text{ is a man who walked in, in }w  \wedge (w,g) \in c_\top}\)
#+end_exe

- Is \(x\) still novel with respect to \(c'\)? No! That's because \(c'\) places constraints \(x\); namely, it will contain a world-assignment pair \((w,g)\) where \(g_x\) is a man who walked in, in \(w\), but it won't contain a world-assignment pair \((w,g')\), where \(g'\) differs minimally from \(g\) in that \(g'_x\) isn't a man who walked in, in \(w\).
- The intuition that definition [[def:novelty]] captures is therefore whether or not a given file places constraints on the value of a discourse referent.
- What Heim goes on to suggest is that update of a context \(c\) with a sentence containing an indefinite indexed \(x\), such as "a\(^x\) man walked in" is defined just in case \(x\) is novel wrt \(c\).
- Consequently, if we have a sequence of utterances such as a "a\(^x\) man walked in; a\(^y\) man sat down", \(x \neq y\), otherwise updating \(c[\text{a}^x\text{ man walked in}]\) with "a\(^y\) man sat down" will be undefined.
  
** Familiarity

- A wholly derivative notion, which we'll use for the semantics of definites, is /familiarity/:

#+begin_definition def:fam
Familiarity of a variable with respect to a file.
\[\mathbf{fam}_F(x) := \neg\ \mathbf{nov}_F(x) \]
#+end_definition

- For sentences such as "He\(_x\) sat down"? Ignoring phi features, we can say that pronouns indexed \(x\) require that \(x\) /not/ be novel with respect to the file context, i.e., that the file context places constraints on the identity of \(x\).
- As we've discussed, one way in which a variable \(x\) can become familiar with respect to a file context is via a previous assertion involving a variable indexed \(x\).
- Heim suggests that variables can also become novel if the file context becomes constrained by salient features of the environment, in order to account for deictic pronouns.
  
** Discourse anaphora and discourse sequencing

- The notion of /novelty/ is crucially defined relative to /files/ rather than individual evaluation points.
  * Note that there's no way to determine, just by looking at individual Heimian evaluation points, whether or not a variable is novel with respect to the file at which a sentence is evaluated.
- Since the novelty requirement is taken to be induced by a linguistic feature of particular sentences (i.e., indefiniteness), there is apparently no escape from treating sentences as functions from files to files (i.e., CCPs).
- The CCP of a sentence containing an indefinite:

#+name: ex:ccp-heim1
#+begin_exe
\ex \(\begin{aligned}[t]
&\text{A}^x\text{ man walked in}\\
&\Rightarrow \lambda F \,.\,\begin{cases}
\set{(w,g)|(w,g) \in F \wedge g_x \text{ a man who walked in in }w }&\mathbf{nov}_F(x)\\
\text{undefined}&\text{else}  
\end{cases}
\end{aligned}\)
#+end_exe

- The CCP of a sentence containing a pronoun:

#+name: ex:ccp-heim2
#+begin_exe
\ex \(\begin{aligned}[t]
&\text{He}_x\text{ sat down}\\
&\Rightarrow \lambda F\,.\,\begin{cases}
\set{(w,g)|(w,g) \in F \wedge g_x \text{ sat down in }w  }&\mathbf{fam}_F(x)\\
\text{undefined}&\text{else}  
\end{cases}
\end{aligned}\)
#+end_exe

- In FCS, the connection between assertion and semantic values is extremely direct. Update simply amounts to passing the file context in as the argument of the CCP.

#+begin_definition
Heim's bridge principle.

Asserting a sentence \(\phi \) at context \(c\) results in an updated context \(c[\phi]\), defined as follows:
\[c[\phi] := \eval*{\phi}(c)\]
#+end_definition

- Successive assertions give rise to successive update of the context.
- At the heart of the account of discourse anaphora is the fact that a sentence with an indefinite such as "A\(^x\) man walked in" renders \(x\) no longer novel with respect to the updated file, satisfying the preconditions of a sentence such as "He\(_x\) sat down".

\[\begin{aligned}[t]
&c[\text{a}^x\text{ man walked in}]\\
&= \begin{cases}
\set{(w,g)|(w,g) \in c \wedge g_x \text{ a man who walked in in }w )}&\mathbf{nov}_c(x)\\
\text{undefined}&\text{else}
\end{cases}
\end{aligned}\]

- If update is successful, the result is an updated context \(c'\), such that \(x\) is no longer novel with respect to.
- This is because \(c'\) discriminates between assignments which differ only with respect to \(x\) - \((w,g)\) is in \(c'\), where \(g_x\) is a man who walked in in \(w\), whereas \((w,g')\) isn't in \(c'\), where \(g'\) is any assignment that minimally differs from \(g\) in mapping \(x\) to an individual that isn't a man who walked in in \(w\). 

\[c'[\text{he}_x\text{ sat down}] = \begin{cases}
\set{(w,g)|(w,g) \in c' \wedge g_x \text{ sat down in }w }&\mathbf{fam}_c(x)\\
\text{undefined}&\text{else}
\end{cases}
\]

- Since this update is guaranteed to be defined, successive update has the following result:

\[\begin{aligned}[t]
&c[\text{a}^x\text{ man walked in}][\text{he}_x\text{ sat down}]\\
&= \begin{cases}
\set{(w,g)|(w,g) \in c \wedge g_x \text{ a man who walked in in }w  \wedge g_x \text{ sat down in }w )}&\mathbf{nov}_c(x)\\
\text{undefined}&\text{else}  
\end{cases}
\end{aligned}\]

- The intuition here is that successive update amounts to passing the context as the file argument of the first sentence, and then passing the resulting output file as the file argument of the second sentence.
- We can define an operator to perform successive update. This turns out to just be function composition. We'll write it as \(;\), and it will play a prominent role in FCS.[fn:4][fn:7]

#+begin_definition
The dynamic sequencing operator \(;\).

\[p;q := \lambda F\,.\,q(p(F))\]
#+end_definition

- At this point, it will be useful to define some types. Let's use \(T\) as the type of a CCP.
- The dynamic sequencing operator is of type \(T \to T \to T\).
- The sequencing operator famously serves as the meaning of conjunction in FCS:

#+name: def:conj
#+begin_exe
\ex \(\text{and} \Rightarrow \lambda q\,.\,\lambda p\,.\,p ; q\)\hfill\(T \to T \to T\)
#+end_exe

- We'll have more to say about other logical vocabulary in FCS as we progress.
- A direct consequence of this definition is that successive update \(c[\phi][\psi]\) is exactly equivalent to \(c[\phi \text{ and }\psi]\). 
- Since dynamic sequencing is just function composition, it inherits the logical properties of function composition, e.g., it is associative. This means we'll often omit parentheses when sequencing.

\[(\phi ; \psi) ; \pi \iff \phi ; (\psi ; \pi)\]

- Both of the following are equivalent:

#+name: ex:assoc
#+begin_exe
\ex A\(^x\) man walked in and he\(_x\) sat down. He\(_x\) started fidgeting.
\ex A\(^x\) man walked in. He\(_x\) sat down and he\(_x\) started fidgeting.
#+end_exe

- Similarly, dynamic sequencing is not necessarily commutative (although some CCPs commute). This reflects the fact that some CCPs can set up the preconditions for other CCPs to apply.

#+name: ex:comm
#+begin_exe
\ex A\(^x\) man walked in and he\(_x\) sat down.
\ex ?He\(_x\) walked in and a\(^x\) man sat down.<<ex:comm2>>
#+end_exe

- FCS predicts the CCP of ([[ex:comm2]]) to be undefined for /any/ file context. 
- It's often assumed that FCS (and dynamic semantics more generally) explains why discourse anaphora displays a left-to-right bias, as illustrated by ([[ex:comm]]).
  
* Next week

- An alternative grounding of novelty vs. familiarity in partial assignments.
- Donkey anaphora in FCS.

#+print_bibliography:

* Footnotes

[fn:9] See [cite:@Chierchia1995] for a detailed comparison. 

[fn:1] \(g[x \to  a]\) is the unique assignment that is identical to \(g\), except for mapping \(x\) to \(a\).

[fn:2] We use \(*\) as a wildcard over values (i.e., an implicitly existentially-quantified variable). 

[fn:4] In more traditional mathematical notation, we'd write this as \(\psi \circ \phi\). I prefer \(\phi ; \psi\), as it more directly reflects information flow in a dynamic setting. 

[fn:7] [cite:@Chierchia1995] goes as far as to suggest that a semantics is /dynamic/ iff the meaning of conjunction is function composition. We'll see many reasons to reject this characterization in the following classes.


